version: "3.7"

services:
  app:
    build: .
    ports:
      - "8888:8888"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ashish
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: learning
    ports:
      - 5433:5432
    networks:
      - s-network
    volumes:
      - postgres-s-volume:/var/lib/postgresql/data


networks:
  s-network:
    driver: bridge


volumes:
  postgres-s-volume: